apiVersion: v1
kind: Service
metadata:                                #元数据
  name: microservice-fenqu-customer                           #service的名称
  namespace: chengyiwu                      #命名空间
  labels:                                #自定义标签属性列表
    name: chengyiwu
  annotations:                           #自定义注解属性列表
    name: chengyiwu
spec:                                    #详细描述
  selector:                            #label selector配置，将选择具有label标签的Pod作为管理 范围
    app: fenqu-customer
  type: NodePort                           #service的类型，指定service的访问方式，默认为clusterIp
  #clusterIP: string                      #虚拟服务地址
  #sessionAffinity: string                #是否支持session
  ports:                                 #service需要暴露的端口列表
  - name: http                         #端口名称
    protocol: TCP                     #端口协议，支持TCP和UDP，默认TCP
    port: 9762                            #服务监听的端口号
    targetPort: 9763                      #需要转发到后端Pod的端口号
    nodePort: 31000                         #当type = NodePort时，指定映射到物理机的端口号
---
apiVersion: v1
kind: Deployment
metadata:                                #元数据
  name: microservice-fenqu-customer                           #service的名称
  namespace: chengyiwu                      #命名空间
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fenqu-customer
  template:          #replicaSet发现Pod不足时,使用此模板定义的规则,创建Pod.
    metadata:
      labels:        #每次创建的Pod都打上下面两个label
        app: fenqu-customer
    spec:
      containers:
      - name: microservice-fenqu-customer
        image: hub.ebupt.com/txcyapi/microservice-fenqu-customer.jar:0.0.1
        ports:
        - name: http
          containerPort: 9763